export const get = (postcode) => fetch('//api.postcodes.io/postcodes/' + postcode)
    .then((response) => response.ok ? response : Promise.reject())
    .catch(() => fetch(`//api.postcodes.io/outcodes/${postcode}/nearest`))
    .then((data) => data.json())
    .then(({ result }) => Array.isArray(result) ? result[0] : result)
    .then(({ latitude, longitude }) => fetch(`//data.police.uk/api/crimes-street/all-crime?lat=${latitude}&lng=${longitude}`))
    .then((data) => data.json())
